import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv
from scrapers.naukri_scraper import scrape_naukri
from scrapers.indeed_scraper import scrape_indeed

def create_html_email(jobs):
    """Formats the list of jobs into a beautiful HTML email body."""
    
    if not jobs:
        return "<p>No relevant jobs found today. Keep trying!</p>"

    # Basic inline CSS for better email client compatibility
    html = """
    <html>
    <head>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f4f4f4; }
        .container { max-width: 800px; margin: auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }
        .header { background-color: #4A90E2; color: #ffffff; padding: 20px; text-align: center; }
        .header h1 { margin: 0; }
        .job-list { padding: 20px; }
        .job-card { border-bottom: 1px solid #eeeeee; padding: 15px 0; }
        .job-card:last-child { border-bottom: none; }
        .job-card h2 { margin: 0 0 5px 0; font-size: 18px; }
        .job-card h2 a { color: #4A90E2; text-decoration: none; }
        .job-card p { margin: 0 0 5px 0; color: #555555; }
        .job-card .company { font-weight: bold; color: #333; }
        .job-card .experience { display: inline-block; padding: 3px 8px; font-size: 12px; border-radius: 12px; background-color: #F0F7FF; color: #0066CC; margin-right: 5px; }
        .job-card .source-tag { display: inline-block; padding: 3px 8px; font-size: 12px; border-radius: 12px; font-weight: bold; }
        .naukri { background-color: #EBF5FF; color: #004D99; }
        .indeed { background-color: #E8F3FF; color: #2557A7; }
        .footer { background-color: #f4f4f4; color: #888888; padding: 15px; text-align: center; font-size: 12px; }
    </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Your Curated Job Digest (0-2 Years Experience) 📄</h1>
            </div>
            <div class="job-list">
    """

    for job in jobs:
        source_class = 'naukri' if job['source'] == 'Naukri' else 'indeed'
        experience = job.get('experience', 'Entry Level')
        html += f"""
        <div class="job-card">
            <h2><a href="{job['link']}" target="_blank">{job['title']}</a></h2>
            <p><span class="company">{job['company']}</span> - {job['location']}</p>
            <p><span class="experience">{experience}</span> <span class="source-tag {source_class}">{job['source']}</span></p>
        </div>
        """
    
    html += """
            </div>
            <div class="footer">
                <p>This email was automatically generated by the Job Scraper Bot.</p>
            </div>
        </div>
    </body>
    </html>
    """
    return html

def send_email(receiver_email, jobs_html):
    """Sends the HTML email to the specified receiver."""
    
    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_PASSWORD")

    if not sender_email or not sender_password:
        print("❌ Error: Sender email or password not found in .env file.")
        return

    message = MIMEMultipart("alternative")
    message["Subject"] = "✨ Your Daily Job Digest (0-2 Yrs Exp) is Here!"
    message["From"] = sender_email
    message["To"] = receiver_email

    # Attach the HTML content
    message.attach(MIMEText(jobs_html, "html"))

    try:
        print(f"📬 Sending email to {receiver_email}...")
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()  # Secure the connection
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, receiver_email, message.as_string())
        print("✅ Email sent successfully!")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

def main():
    """Main function to run the job scraper and notifier."""
    load_dotenv(dotenv_path="email_password.env")

    # --- Get user input from terminal ---
    print("--- Job Scraper & Notifier (0-2 Years Experience) ---")
    receiver_email = input("✉️  Enter the receiver's email address: ")
    
    # Updated prompts to indicate they are optional
    naukri_url = input("🔗 Enter Naukri URL (or press Enter to use default 0-2 years experience jobs): ")
    indeed_url = input("🔗 Enter Indeed URL (or press Enter to use default entry-level jobs): ")
    print("-" * 30)

    all_jobs = []

    # --- Scrape Jobs Conditionally ---
    # Always try to scrape from both sources, using default URLs if none provided
    print("🔍 Searching for jobs with 0-2 years experience requirement...")
    
    # Scrape from Naukri
    naukri_jobs = scrape_naukri(naukri_url)
    all_jobs.extend(naukri_jobs)
    print(f"✅ Found {len(naukri_jobs)} jobs on Naukri.")
    
    # Scrape from Indeed
    indeed_jobs = scrape_indeed(indeed_url)
    all_jobs.extend(indeed_jobs)
    print(f"✅ Found {len(indeed_jobs)} jobs on Indeed.")
    
    # --- Format and Send Email ---
    if all_jobs:
        print(f"\n🎯 Found a total of {len(all_jobs)} jobs matching 0-2 years experience criteria.")
        print("📧 Preparing email...")
        email_body = create_html_email(all_jobs)
        send_email(receiver_email, email_body)
    else:
        print("\n⚠️ No jobs found matching the 0-2 years experience criteria. No email will be sent.")
        print("💡 Tips:")
        print("  - Try different job search URLs")
        print("  - Check if the websites' HTML structure has changed")
        print("  - Ensure you have a stable internet connection")
    
    print("🎉 Process finished.")


if __name__ == "__main__":
    main()